version: "3" 
#NETWORK 
networks:  
  my-network: 
    driver: bridge 
services:  
  loopback-api-service: 
    container_name: 'loopback-api-service' 
    build:  
      context: ./lb-4-tutorial
      dockerfile: Dockerfile 
    image: lbapi
    restart: always 
    ports: 
      - 3001:3001 
    networks: 
      - my-network