@startuml read todo user sequence

header READ TODO OF USER | ADMIN SEQUENCE
actor Admin 
control server
database user

opt READ: Admin read user todo
  Admin -> server: GET /admins/readUserTodo{id}
  activate server
  server -> server: check token
  activate server #DarkBlue
  alt <font color=red>token invalid</font>
    server --> Admin: 401, unauthorized error
    deactivate server
  else <font color=green>token valid</font>
    server -> server: decrypt token to get profile of user
    activate server #DarkBlue
    alt <font color=red>profile is Null</font>
      server --> Admin : 401, request failed
      deactivate server
      else <font color=green>has profile</font>
        server -> server: check isAdmin
        activate server #DarkBlue
      alt <font color=red>is not admin</font>
        server --> Admin: 403, forbidden error
        deactivate server
      else <font color=green>is admin</font>
      activate user
      server -> user: find user with userId
      alt <font color=red>have error</font>
        user --> server: error
        server --> Admin: 500, internal error

        alt <font color=red>user not found</font>
        user --> server: request rejected
        server --> Admin: 404, user not found
      else <font color=green>found user</font>
          user --> server: response todos of user
      else <font color=green>success</font>
          server --> Admin: 200, success, response todos data
        end
      end
    end
  end
  end
  
    deactivate server


@enduml